export const styles = {
  fieldErrorWrap: "mt-1.5 flex items-center gap-1.5",
  fieldErrorIcon: "h-3.5 w-3.5 shrink-0 text-red-500",
  fieldErrorText: "whitespace-pre-line text-xs leading-snug text-red-500",
  phoneSelectWrap: "relative flex",
  phoneSelectButton:
    "flex h-10 min-w-[110px] flex-shrink-0 items-center gap-2 rounded-l-xl border border-r-0 bg-slate-50 px-3 transition-colors hover:bg-slate-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-emerald-500",
  phoneSelectInput:
    "flex-1 h-10 rounded-r-xl border bg-white px-3 text-sm transition-colors placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-emerald-500",
  phoneSelectBorderError: "border-red-400 bg-red-50/40 focus:ring-red-400",
  phoneSelectBorderDefault: "border-slate-200 hover:border-slate-300",
  phoneFlag: "rounded-sm object-cover",
  phoneFlagMenu: "shrink-0 rounded-sm object-cover",
  phoneCode: "text-sm font-medium tabular-nums text-slate-700",
  phoneChevron: "h-3.5 w-3.5 text-slate-400 transition-transform",
  phoneChevronOpen: "rotate-180",
  phoneDropdown:
    "absolute left-0 top-full z-50 mt-1.5 w-72 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-2xl",
  phoneDropdownHeader: "border-b border-slate-100 p-2",
  phoneSearchWrap: "relative",
  phoneSearchIcon:
    "pointer-events-none absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400",
  phoneSearchInput:
    "h-8 w-full rounded-lg border border-slate-200 bg-slate-50 pl-8 pr-3 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500",
  phoneList: "max-h-56 overflow-y-auto py-1",
  phoneNoResults: "px-4 py-3 text-center text-sm text-slate-400",
  phoneListItem: "flex cursor-pointer items-center gap-3 px-3 py-2.5 text-sm transition-colors",
  phoneListItemActive: "bg-emerald-50",
  phoneListItemIdle: "hover:bg-slate-50",
  phoneCountryName: "flex-1 font-medium text-slate-800",
  phoneCountryCode: "text-xs font-mono tabular-nums text-slate-400",
  phoneCheckIcon: "h-3.5 w-3.5 shrink-0 text-emerald-600",
  multiSelectWrap: "overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm",
  multiSelectHeader:
    "flex items-center justify-between border-b border-slate-100 bg-slate-50/80 px-4 py-3",
  multiSelectHeaderLeft: "flex items-center gap-2",
  multiSelectTitle: "text-sm font-semibold text-slate-800",
  multiSelectPill: "rounded-full px-2 py-0.5 text-xs font-semibold",
  multiSelectHeaderRight: "flex items-center gap-1",
  multiSelectClearButton:
    "rounded-md px-2.5 py-1 text-xs font-medium text-slate-500 transition-colors hover:bg-slate-100 hover:text-slate-800",
  multiSelectToggleButton:
    "rounded-md p-1.5 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-600",
  multiSelectToggleIcon: "h-4 w-4",
  multiSelectSelectedWrap: "flex flex-wrap gap-1.5 border-b border-slate-100 px-4 py-3",
  multiSelectBadge:
    "inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-xs font-medium",
  multiSelectBadgeBusyIcon: "ml-0.5 h-3 w-3 animate-spin opacity-60",
  multiSelectBadgeRemoveButton: "ml-0.5 transition-colors",
  multiSelectBadgeRemoveIcon: "h-3 w-3",
  multiSelectSearchSection: "border-b border-slate-100 px-4 py-3",
  multiSelectSearchWrap: "relative",
  multiSelectSearchIcon:
    "pointer-events-none absolute left-3 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400",
  multiSelectSearchInput:
    "h-9 w-full rounded-lg border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm transition-colors focus:bg-white focus:outline-none focus:ring-2 focus:ring-emerald-500",
  multiSelectOptions: "max-h-56 overflow-y-auto",
  multiSelectEmpty: "px-4 py-6 text-center text-sm text-slate-400",
  multiSelectOption:
    "flex cursor-pointer items-center gap-3 border-b border-slate-50 px-4 py-2.5 transition-colors last:border-0",
  multiSelectOptionIdle: "hover:bg-slate-50",
  multiSelectOptionBusy: "pointer-events-none opacity-60",
  multiSelectCheckbox: "border-slate-300",
  multiSelectOptionText: "text-sm text-slate-700",
  multiSelectBusyIcon: "ml-auto h-3.5 w-3.5 animate-spin text-slate-400",
  overviewFieldWrap: "rounded-xl border border-slate-100 bg-slate-50/60 px-4 py-3",
  noticeError: "flex items-center gap-3 rounded-xl border-red-200 bg-red-50 px-4 py-3",
  noticeSuccess: "flex items-center gap-3 rounded-xl border-emerald-200 bg-emerald-50 px-4 py-3",
  noticeErrorText: "m-0 text-sm text-red-700",
  noticeSuccessText: "m-0 text-sm text-emerald-700",
  inputLabel: "text-sm font-medium text-slate-700",
  textInput: "rounded-xl border-slate-200 focus:ring-emerald-500",
  readOnlyInputBase: "rounded-xl",
  healthEmptyText: "text-sm italic text-slate-400",
  deleteButtonIcon: "mr-2 h-4 w-4",
  deleteConfirmHighlight: "font-mono font-bold text-red-600",
  deleteConfirmInput: "rounded-xl border-red-200 focus:ring-red-400",
  accent: {
    emerald: {
      badge: "border-amber-200 bg-amber-50 text-amber-800",
      badgeX: "text-amber-500 hover:text-amber-800",
      pill: "bg-amber-100 text-amber-700",
      row: "bg-amber-50/60 hover:bg-amber-50",
      checkbox: "data-[state=checked]:border-amber-500 data-[state=checked]:bg-amber-500",
      rowText: "font-medium text-amber-900",
    },
    sky: {
      badge: "border-sky-200 bg-sky-50 text-sky-800",
      badgeX: "text-sky-500 hover:text-sky-800",
      pill: "bg-sky-100 text-sky-700",
      row: "bg-sky-50/60 hover:bg-sky-50",
      checkbox: "data-[state=checked]:border-sky-500 data-[state=checked]:bg-sky-500",
      rowText: "font-medium text-sky-900",
    },
  },
  cls001: "min-h-[60vh] flex items-center justify-center p-8",
  cls002: "flex items-center gap-3 text-slate-500 text-sm font-medium",
  cls003: "h-5 w-5 animate-spin text-emerald-500",
  cls004: "space-y-6",
  cls005: "text-2xl font-bold tracking-tight text-slate-900",
  cls006: "mt-1 text-sm text-slate-500",
  cls007: "h-4 w-4 shrink-0 text-red-500",
  cls008: "h-4 w-4 shrink-0 text-emerald-600",
  cls009:
    "grid h-auto w-full grid-cols-2 gap-1.5 rounded-2xl border border-slate-200 bg-slate-100/70 p-1.5 md:grid-cols-4",
  cls010: [
    "flex items-center justify-center gap-1.5 rounded-xl px-3 py-2 text-sm font-medium text-slate-500 transition-all duration-200",
    "data-[state=active]:bg-white data-[state=active]:text-slate-900 data-[state=active]:shadow-sm data-[state=active]:ring-1 data-[state=active]:ring-slate-200/80",
    "hover:text-slate-700",
  ].join(" "),
  cls011: "h-4 w-4 shrink-0",
  cls012: "rounded-2xl border border-slate-200 bg-white shadow-sm",
  cls013: "text-lg font-semibold text-slate-900",
  cls014: "space-y-5",
  cls015: "grid grid-cols-1 gap-5 md:grid-cols-2",
  cls016: "text-[11px] font-semibold uppercase tracking-widest text-slate-400",
  cls017: "mt-0.5 text-sm font-medium text-slate-800",
  cls018: "space-y-1.5",
  cls019: "text-sm font-semibold text-slate-700",
  cls020: "mt-2 flex flex-wrap gap-1.5",
  cls021:
    "rounded-full border border-amber-300 bg-amber-50 px-3 py-0.5 text-xs font-semibold text-amber-800",
  cls022: "mt-1 text-sm italic text-slate-400",
  cls023: "rounded-full border border-sky-300 bg-sky-50 px-3 py-0.5 text-xs font-semibold text-sky-800",
  cls024: "flex items-center gap-3 rounded-xl border border-violet-200 bg-violet-50 px-4 py-3",
  cls025: "text-[11px] font-semibold uppercase tracking-widest text-violet-500",
  cls026: "text-sm font-semibold text-violet-900",
  cls027: "cursor-not-allowed bg-slate-100 text-slate-400",
  cls028: "mt-1 text-xs text-slate-400",
  cls029:
    "mt-2 w-full rounded-xl bg-emerald-600 py-2.5 text-sm font-semibold text-white shadow-sm transition-all hover:bg-emerald-700 active:scale-[0.99]",
  cls030: "mr-2 h-4 w-4 animate-spin",
  cls031: "rounded-2xl border border-slate-200 bg-white shadow-sm",
  cls032: "flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3",
  cls033: "h-4 w-4 shrink-0 text-emerald-600",
  cls034: "m-0 text-sm text-slate-600",
  cls035: "space-y-3",
  cls036: "text-sm font-semibold text-slate-800",
  cls037:
    "grid grid-cols-1 gap-2 rounded-xl border border-slate-100 bg-slate-50 p-3 md:grid-cols-2 lg:grid-cols-3",
  cls038: "text-sm text-slate-700",
  cls039: "ml-auto h-3.5 w-3.5 animate-spin text-slate-400",
  cls040: "grid grid-cols-1 gap-2 rounded-xl border border-slate-100 bg-slate-50 p-3 md:grid-cols-2",
  cls041: "rounded-xl border border-violet-200 bg-violet-50 p-4",
  cls042: "text-sm font-semibold text-violet-900",
  cls043: "mt-3 flex items-center gap-3",
  cls044: "h-5 w-5 border-violet-400 data-[state=checked]:border-violet-600 data-[state=checked]:bg-violet-600",
  cls045: "cursor-pointer text-sm text-violet-800",
  cls046: "h-4 w-4 animate-spin text-violet-600",
  cls047: "rounded-2xl border border-red-200 bg-white shadow-sm",
  cls048: "text-lg font-semibold text-red-700",
  cls049: "flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-3",
  cls050: "h-4 w-4 shrink-0 text-red-600",
  cls051: "m-0 text-sm text-red-800",
  cls052:
    "mt-2 w-full rounded-xl bg-red-600 py-2.5 text-sm font-semibold text-white shadow-sm transition-all hover:bg-red-700 active:scale-[0.99]",
  cls053: "flex gap-3 pt-1",
  cls054: "flex-1 rounded-xl",
  cls055: "flex-1 rounded-xl bg-red-600 text-white hover:bg-red-700",
};
